# Generated by Django 4.2.1 on 2023-05-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_nugget_tag_delete_person_nugget_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nugget',
            name='tags',
        ),
        migrations.AlterField(
            model_name='nugget',
            name='datatype',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nugget',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nugget',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
