# Generated by Django 4.2.1 on 2023-05-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_nugget_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nugget',
            name='tags',
        ),
    ]
