# Generated by Django 4.2.1 on 2023-05-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_nugget_tags'),
    ]

    operations = [
    ]
